name: Deploy

on:
  pull_request:
      branches:  
        - main

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install
      - name: check lint
        run: pnpm lint
      - name: install playwright
        run: npx playwright install
      - name: run playwright tests
        env:
          HEADLESS: true
        run: pnpm playwright test
      - name: build app
        run: pnpm run build
      - name: Setup SSH
        run: |
          mkdir -p ~/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/id_rsa.pub
          chmod 600 ~/id_rsa
          chmod 600 ~/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          rsync -vrm  .output/* ${{ secrets.USER_IP }}:/
